# Generated by Django 2.1.1 on 2018-09-10 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_ul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='type_money',
            field=models.CharField(choices=[('note', 'банкнота'), ('coin', 'монета'), ('', '')], default='coin', max_length=7),
        ),
        migrations.AlterField(
            model_name='money',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 11, 59, 59, 702257), verbose_name='date start'),
        ),
    ]
