# Generated by Django 2.1.1 on 2018-09-17 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_ul', '0002_auto_20180910_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 19, 54, 26, 936945), verbose_name='date start'),
        ),
    ]
