# Generated by Django 2.1.1 on 2018-09-18 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_ul', '0003_auto_20180917_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 19, 44, 11, 175781), verbose_name='date start'),
        ),
        migrations.AlterField(
            model_name='money',
            name='type_money',
            field=models.CharField(choices=[('note', 'банкнота'), ('coin', 'монета'), ('medal', 'медали'), ('', '')], default='coin', max_length=7),
        ),
    ]
