# Generated by Django 2.1.1 on 2018-09-23 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_ul', '0004_auto_20180918_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='money',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 16, 44, 39, 334960), verbose_name='date start'),
        ),
    ]
